server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/backend
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  data:
    redis:
      host: localhost
      port: 6379
      password: password